# Generated by Django 3.1.3 on 2020-11-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='id',
            field=models.IntegerField(default=True, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='search',
            name='link',
            field=models.CharField(max_length=100, verbose_name='Запрос'),
        ),
    ]
