# Generated by Django 3.1.3 on 2020-11-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_auto_20201123_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='link',
            new_name='request',
        ),
        migrations.AlterField(
            model_name='search',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
