# Generated by Django 3.1.3 on 2020-11-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0004_auto_20201123_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='records_cnt',
            field=models.IntegerField(default=0, verbose_name='Количество записей'),
        ),
    ]
