# Generated by Django 3.1.3 on 2020-11-24 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0005_search_records_cnt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='records_cnt',
        ),
    ]
